---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gravitino.serviceName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.gravitino.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.gravitino.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.gravitino.serviceName }}
    spec:
      containers:
      - name: gravitino
        image: "{{ .Values.gravitino.image.repository }}:{{ .Values.gravitino.image.tag }}"
        ports:
        - containerPort: 8090
        - containerPort: 9001
        command: ["/bin/bash", "/tmp/gravitino/init.sh"]
        env:
          {{- toYaml .Values.gravitino.env | nindent 12 }}
        volumeMounts:
        - name: gravitino-healthcheck-scripts
          mountPath: /tmp/healthcheck
        - name: gravitino-artifacts
          mountPath: /tmp/gravitino
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /tmp/healthcheck/gravitino-healthcheck.sh
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        resources:
          {{- toYaml .Values.gravitino.resources | nindent 12 }}
      initContainers:
      - name: wait-for-hive
        image: "{{ .Values.gravitino.image.repository }}:{{ .Values.gravitino.image.tag }}"
        command: ["/bin/bash", "/tmp/healthcheck/hive-healthcheck.sh"]
        env:
          {{- toYaml .Values.gravitino.env | nindent 12 }}
        volumeMounts:
        - name: gravitino-healthcheck-scripts
          mountPath: /tmp/healthcheck
      - name: wait-for-mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        command: ["/bin/bash", "/tmp/healthcheck/mysql-healthcheck.sh"]
        env:
          {{- toYaml .Values.mysql.env | nindent 12 }}
        volumeMounts:
        - name: gravitino-healthcheck-scripts
          mountPath: /tmp/healthcheck
      volumes:
      - name: gravitino-artifacts
        hostPath:
          path: {{ printf "%s/init/gravitino/" .Values.projectRoot }}
          type: DirectoryOrCreate
      - name: gravitino-healthcheck-scripts
        hostPath:
          path: {{ printf "%s/healthcheck/" .Values.projectRoot }}
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gravitino.serviceName }}
spec:
  selector:
    app: {{ .Values.gravitino.serviceName }}
  ports:
  - port: 8090
    targetPort: 8090
    name: api
  - port: 9001
    targetPort: 9001
    name: debug
