apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.jupyter.serviceName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.jupyter.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.jupyter.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.jupyter.serviceName }}
    spec:
      containers:
        - name: jupyter
          image: "{{ .Values.jupyter.image.repository }}:{{ .Values.jupyter.image.tag }}"
          ports:
          - containerPort: 8888
          command: ["/bin/bash", "/tmp/gravitino/init.sh"]
          securityContext:
            privileged: true
            runAsUser: 0
          env:
            {{- toYaml .Values.jupyter.env | nindent 12 }}
          volumeMounts:
            - name: jupyter-artifacts
              mountPath: /tmp/gravitino
            - name: healthcheck-script
              mountPath: /tmp/healthcheck
          resources:
            {{- toYaml .Values.jupyter.resources | nindent 12 }}
      initContainers:
        - name: wait-for-gravitino
          image: "{{ .Values.jupyter.image.repository }}:{{ .Values.jupyter.image.tag }}"
          command: ["/bin/bash", "/tmp/healthcheck/gravitino-healthcheck.sh"]
          env:
            {{- toYaml .Values.jupyter.env | nindent 12 }}
          volumeMounts:
            - name: healthcheck-script
              mountPath: /tmp/healthcheck
        - name: wait-for-hive
          image: "{{ .Values.hive.image.repository }}:{{ .Values.hive.image.tag }}"
          command: ["/bin/bash", "/tmp/healthcheck/hive-healthcheck.sh"]
          env:
            {{- toYaml .Values.jupyter.env | nindent 12 }}
          volumeMounts:
            - name: healthcheck-script
              mountPath: /tmp/healthcheck
        - name: wait-for-trino
          image: "{{ .Values.trino.image.repository }}:{{ .Values.trino.image.tag }}"
          command: ["/bin/bash", "/tmp/healthcheck/trino-healthcheck.sh"]
          env:
            {{- toYaml .Values.jupyter.env | nindent 12 }}
          volumeMounts:
            - name: healthcheck-script
              mountPath: /tmp/healthcheck
      volumes:
        - name: jupyter-artifacts
          hostPath:
            path: {{ printf "%s/init/jupyter/" .Values.projectRoot }}
            type: DirectoryOrCreate
        - name: healthcheck-script
          configMap:
            name: healthcheck-script
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jupyter.serviceName }}
spec:
  selector:
    app: {{ .Values.jupyter.serviceName }}
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcheck-script
data:
  {{- range $path, $_ := .Files.Glob "healthcheck/*" }}
  {{ base $path }}: |-
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}