---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jupyter
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}-jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-jupyter
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-jupyter
    spec:
      containers:
        - name: jupyter
          image: "{{ .Values.jupyter.image.repository }}:{{ .Values.jupyter.image.tag }}"
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: init-script
              mountPath: /tmp/gravitino
          resources:
            {{- toYaml .Values.jupyter.resources | nindent 10 }}
      volumes:
        - name: init-script
          configMap:
            name: {{ .Release.Name }}-jupyter-init-script

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jupyter
spec:
  type: ExternalName
  externalName: jupyter
  selector:
    app: {{ .Release.Name }}-jupyter
  ports:
    - port: 8888
      targetPort: 8888

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-jupyter-init-script
data:
{{ (.Files.Glob "init/jupyter/*").AsConfig | indent 4 }}
