# templates/mysql.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.serviceName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.mysql.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.serviceName }}
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        ports:
        - containerPort: 3306
        env:
          {{- toYaml .Values.mysql.env | nindent 12 }}
        args:
        - --default-authentication-plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_general_ci
        - --explicit_defaults_for_timestamp=true
        - --lower_case_table_names=1
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        resources:
          {{- toYaml .Values.mysql.resources | nindent 12 }}
      volumes:
      - name: init-script
        configMap:
          name: mysql-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.serviceName }}
spec:
  selector:
    app: {{ .Values.mysql.serviceName }}
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
{{ (.Files.Glob "init/mysql/*").AsConfig | indent 4 }}
