---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgresql.serviceName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.postgresql.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgresql.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.serviceName }}
    spec:
      containers:
      - name: postgresql
        image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
        ports:
        - containerPort: 5432
        env:
          {{- toYaml .Values.postgresql.env | nindent 12 }}
        volumeMounts:
        - name: postgresql-init-script
          mountPath: /docker-entrypoint-initdb.d
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 12 }}
      volumes:
      - name: postgresql-init-script
        configMap:
          name: postgresql-init-script
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.serviceName }}
spec:
  selector:
    app: {{ .Values.postgresql.serviceName }}
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-script
data:
  {{- range $path, $_ := .Files.Glob "init/postgres/*" }}
  {{ base $path }}: |-
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}
