# templates/spark.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.spark.serviceName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.spark.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.spark.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.spark.serviceName }}
    spec:
      containers:
      - name: spark
        image: "{{ .Values.spark.image.repository }}:{{ .Values.spark.image.tag }}"
        ports:
        - containerPort: 4040
        command: ["/bin/bash", "/tmp/spark/init.sh"]
        env:
          {{- toYaml .Values.spark.env | nindent 12 }}
        volumeMounts:
        - name: spark-artifacts
          mountPath: /tmp/spark
        - name: spark-common-artifacts
          mountPath: /tmp/common
        resources:
          {{- toYaml .Values.spark.resources | nindent 12 }}
      volumes:
      - name: spark-artifacts
        hostPath:
          path: {{ printf "%s/init/postgres/" .Values.projectRoot }}
          type: DirectoryOrCreate
      - name: spark-common-artifacts
        hostPath:
          path: {{ printf "%s/init/common/" .Values.projectRoot }}
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.spark.serviceName }}
spec:
  selector:
    app: {{ .Values.spark.serviceName }}
  ports:
  - port: 4040
    targetPort: 4040
